#ifndef _GRAPHICS_X_ERROR_DEFINE_H_
#define _GRAPHICS_X_ERROR_DEFINE_H_

#define GXERROR_INVALID_PARAMETER          87L    // dderror
#define GXERROR_INVALID_MENU_HANDLE        1401L
#define GXERROR_INVALID_INDEX              1413L
#define GXERROR_SETCOUNT_ON_BAD_LB         1433L
#define GXERROR_LB_WITHOUT_TABSTOPS        1434L
#define GXERROR_MENU_ITEM_NOT_FOUND        1456L

#define MOERROR_FMT_OUTOFMEMORY     "%s : Out of memory.\n", __FUNCTION__
#define MOERROR_FMT_INVALIDPARAM    ("%s Error: Invalid param.\n")

#endif // _GRAPHICS_X_ERROR_DEFINE_H_